<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ZfBootstrap\Module'                                    => __DIR__ . '/Module.php',
    'ZfBootstrap\View\Helper\Navigation\BsNavBar'           => __DIR__ . '/src/ZfBootstrap/View/Helper/Navigation/BsNavBar.php',
    'ZfBootstrap\View\Helper\Navigation\BsNavMenu'          => __DIR__ . '/src/ZfBootstrap/View/Helper/Navigation/BsNavMenu.php',
    'ZfBootstrap\View\Helper\Navigation\PluginConfigurator' => __DIR__ . '/src/ZfBootstrap/View/Helper/Navigation/PluginConfigurator.php',
);
